project:
  type: website
  output-dir: _site
website:
  title: Tue Nguyen
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
format:
  html:
    smooth-scroll: true
    theme: 
      dark: superhero
      light: lumen
    css: assets/css/styles.css
    toc: true
    toc-location: right
    page-layout: article
    link-external-newwindow: true
resources:
  - content/**
  - assets/**