project:
  type: website
  output-dir: _site
website:
  title: "Tue Nguyen"
  search: true
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
format:
  html:
    smooth-scroll: true
    theme: 
      dark: [darkly, assets/scss/style-dark.scss]
      light: [flatly, assets/scss/style-light.scss]
    css: assets/css/styles.css
    toc: true
    toc-location: right
    toc-title: On this page
    link-external-newwindow: true
resources:
  - content/**
  - assets/**